export const MoviesData = 
[
 {
           "id": "1",
           "idi": 1008005,
           "title": "The Communion Girl",
           "language": "es",
           "overview": "Spain, late 1980s. Newcomer Sara tries to fit in with the other teens in this tight-knit small town in the province of Tarragona. If only she were more like her extroverted best friend, Rebe. They go out one night at a nightclub, on the way home",
           "image": "https://image.tmdb.org/t/p/original/sP6AO11a7jWgsmT9T8j9EGIWAaZ.jpg",
           "date": "2023-02-10",
           "background": "https://image.tmdb.org/t/p/original/54IXMMEQKlkPXHqPExWy98UBmtE.jpg",
           "gender": "Terror"
       },
       {
           "id": "2",
           "idi": 758323,
           "title": "The Pope's Exorcist",
           "language": "en",
           "overview": "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
           "image": "https://image.tmdb.org/t/p/original/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
           "date": "2023-04-05",
           "background": "https://image.tmdb.org/t/p/original/5Y5pz0NX7SZS9036I733F7uNcwK.jpg",
           "gender": "Terror"
       },
       {
           "id": "3",
           "idi": 980078,
           "title": "Winnie the Pooh: Blood and Honey",
           "language": "en",
           "overview": "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
           "image": "https://image.tmdb.org/t/p/original/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg",
           "date": "2023-01-27",
           "background": "https://image.tmdb.org/t/p/original/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
           "gender": "Terror"
       },
       {
           "id": "5",
           "idi": 1084225,
           "title": "The Park",
           "language": "en",
           "overview": "A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverlan",
           "image": "https://image.tmdb.org/t/p/original/hR1jdCw0A9czgsbp45TASkjjBhA.jpg",
           "date": "2023-03-02",
           "background": "https://image.tmdb.org/t/p/original/cevmHkKqSlrTYqpJ5eaAjml1jec.jpg",
           "gender": "Terror"
       },
       {
           "id": "4",
           "idi": 713704,
           "title": "Evil Dead Rise",
           "language": "en",
           "overview": "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
           "image": "https://image.tmdb.org/t/p/original/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
           "date": "2023-04-12",
           "background": "https://image.tmdb.org/t/p/original/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
           "gender": "Terror"
       },
       {
           "id": "6",
           "idi": 296271,
           "title": "The Devil Conspiracy",
           "language": "en",
           "overview": "The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ",
           "image": "https://image.tmdb.org/t/p/original/2lUYbD2C3XSuwqMUbDVDQuz9mqz.jpg",
           "date": "2023-01-13",
           "background": "https://image.tmdb.org/t/p/original/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg",
           "gender": "Terror"
       },
       {
        "id": "24",
        "idi": 948713,
        "title": "The Last Kingdom: Seven Kings Must Die",
        "language": "en",
        "overview": "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
        "image": "https://image.tmdb.org/t/p/original/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
        "date": "2023-04-14",
        "background": "https://image.tmdb.org/t/p/original/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
        "gender": "Action"
    },
    {
        "id": "25",
        "idi": 677179,
        "title": "Creed III",
        "language": "en",
        "overview": "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove th",
        "image": "https://image.tmdb.org/t/p/original/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
        "date": "2023-03-01",
        "background": "https://image.tmdb.org/t/p/original/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
        "gender": "Action"
    },
    {
        "id": "26",
        "idi": 638974,
        "title": "Murder Mystery 2",
        "language": "en",
        "overview": "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
        "image": "https://image.tmdb.org/t/p/original/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
        "date": "2023-03-28",
        "background": "https://image.tmdb.org/t/p/original/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
        "gender": "Action"
    },
    {
        "id": "27",
        "idi": 603692,
        "title": "John Wick: Chapter 4",
        "language": "en",
        "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old frien",
        "image": "https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        "date": "2023-03-22",
        "background": "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
        "gender": "Action"
    },
    {
        "id": "28",
        "idi": 946310,
        "title": "Pirates Down the Street II: The Ninjas from Across",
        "language": "nl",
        "overview": "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his ",
        "image": "https://image.tmdb.org/t/p/original/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
        "date": "2022-04-20",
        "background": "https://image.tmdb.org/t/p/original/tFaC1Fb1sv1dALB0i9Avi76MHmn.jpg",
        "gender": "Action"
    },
    {
        "id": "29",
        "idi": 700391,
        "title": "65",
        "language": "en",
        "overview": "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
        "image": "https://image.tmdb.org/t/p/original/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
        "date": "2023-03-02",
        "background": "https://image.tmdb.org/t/p/original/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
        "gender": "Action"
    },
    {
        "id": "30",
        "idi": 849869,
        "title": "Kill Boksoon",
        "language": "ko",
        "overview": "At work, she's a renowned assassin. At home, she's a single mom to a teenage daughter. Killing? That's easy. It's parenting that's the hard part.",
        "image": "https://image.tmdb.org/t/p/original/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg",
        "date": "2023-02-17",
        "background": "https://image.tmdb.org/t/p/original/tYcmm8XtzRdcT6kliCbHuWwLCwB.jpg",
        "gender": "Action"
    },
    {
        "id": "31",
        "idi": 842945,
        "title": "Supercell",
        "language": "en",
        "overview": "Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Ro",
        "image": "https://image.tmdb.org/t/p/original/gbGHezV6yrhua0KfAgwrknSOiIY.jpg",
        "date": "2023-03-17",
        "background": "https://image.tmdb.org/t/p/original/m1fgGSLK0WvRpzM1AmZu38m0Tx8.jpg",
        "gender": "Action"
    },
    {
        "id": "32",
        "idi": 1033219,
        "title": "Attack on Titan",
        "language": "en",
        "overview": "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't tr",
        "image": "https://image.tmdb.org/t/p/original/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg",
        "date": "2022-09-30",
        "background": "https://image.tmdb.org/t/p/original/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg",
        "gender": "Action"
    },
    {
        "id": "33",
        "idi": 1048300,
        "title": "Adrenaline",
        "language": "en",
        "overview": "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
        "image": "https://image.tmdb.org/t/p/original/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
        "date": "2022-12-15",
        "background": "https://image.tmdb.org/t/p/original/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
        "gender": "Action"
    },
    {
        "id": "34",
        "idi": 505642,
        "title": "Black Panther: Wakanda Forever",
        "language": "en",
        "overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with ",
        "image": "https://image.tmdb.org/t/p/original/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
        "date": "2022-11-09",
        "background": "https://image.tmdb.org/t/p/original/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
        "gender": "Action"
    },
]